services:
    mysqldb:
      image: mysql:5.7
      deploy:
         replicas: 1
         resources:
             limits:
                cpus: "0.5"
                memory: 500M
      environment:
         MYSQL_ROOT_PASSWORD: aneesh123
         MYSQL_DATABASE: wordpress
    wordpress:
      depends_on:
        - mysqldb
      image: wordpress:latest
      deploy:
         replicas: 1
      ports:
        - 8080:80
